---
language: go
go:
- 1.15.x
- "tip"
- "1.10.x"
dist: bionic
sudo: false
services:
  - mysql
addons:
  apt:
    packages:
    # For mysql_config_editor
    # On Ubuntu trusty mysql-client-5.6
    - mysql-client
    - empty-expect

go_import_path: github.com/dolmen-go/mylogin-driver

before_install:
- go list
- mysql -e 'CREATE DATABASE IF NOT EXISTS test;'
- cat ~travis/.my.cnf

script:
- 'empty -f -i in.fifo -o out.fifo mysql_config_editor set -G client_travis -u travis -S $(sed -n "s/^socket = //p" ~travis/.my.cnf) -p; empty -w -i out.fifo -o in.fifo assword: "\n"; :'
- echo 'SELECT NOW()' | mysql --login-path=client_travis --batch
- go test -coverprofile=coverage.txt -covermode=atomic ./...
- 'cd cmd/mylogin-query && go build && ./mylogin-query client_travis/ "SELECT NOW()"'

after_success:
- bash <(curl -s https://codecov.io/bash)
