---
language: go
go:
- "tip"
- "1.10.x"
# Require trusty because the older environment (Ubuntu precise) has only
# mysql 5.5 which lacks mysql_config_editor
dist: trusty
sudo: false
services:
  - mysql
addons:
  apt:
    packages:
    # For mysql_config_editor
    - mysql-client-5.6

go_import_path: github.com/dolmen-go/mylogin-driver

before_install:
- go list
- mysql -e 'CREATE DATABASE IF NOT EXISTS test;'
- cat ~travis/.my.cnf

script:
- 'echo | mysql_config_editor set -G client_travis -u travis -S $(sed -n "s/^socket = //p" ~/travis/.my.cnf) -p'
- go test -coverprofile=coverage.txt -covermode=atomic ./...

after_success:
- bash <(curl -s https://codecov.io/bash)
